name: BST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install valgrind

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target BST

    - name: Test
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target BST_test
      
    - name: Valgrind
      run: valgrind --leak-check=full ${{github.workspace}}/build/binary_search_tree/test/BST_ut
      
